Update Dell3.yml

diff --git a/.github/workflows/Dell3.yml b/.github/workflows/Dell3.yml
--- a/.github/workflows/Dell3.yml
+++ b/.github/workflows/Dell3.yml
@@ -39,7 +39,28 @@ jobs:
         ref: master
         submodules: 'recursive'
         fetch-depth: '0'
-  
+				
+    - name: Apply commit from DHR60/V2rayNG self_use_build
+      run: |
+        cd ${{ github.workspace }}/V2rayNG
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        #git remote add DHR60 https://github.com/DHR60/V2rayNG.git
+        #echo "Pref dnshost"
+        #git fetch DHR60 self_use_build
+        #git cherry-pick 6ce76ce4b3665ac60cb1fab42620c85afc1e66ff || true
+
+        git remote add DHR60 https://github.com/DHR60/V2rayNG.git
+        git fetch DHR60 self_use_build
+
+        DNS_HOST_SHA=$(git log DHR60/self_use_build --grep="perf. dns host" --format="%H" -n 1)
+
+        if [ -n "$DNS_HOST_SHA" ]; then
+         echo "Found commit: $DNS_HOST_SHA"
+         git cherry-pick $DNS_HOST_SHA || true
+        else
+        echo "Error: No commit found with message 'perf. dns host'"
+        fi
     - name: Set Swap Space
       uses: pierotofy/set-swap-space@master
       with:
