Update Dellll.yml

diff --git a/.github/workflows/Dellll.yml b/.github/workflows/Dellll.yml
--- a/.github/workflows/Dellll.yml
+++ b/.github/workflows/Dellll.yml
@@ -63,10 +63,23 @@ jobs:
         cd ${{ github.workspace }}/V2rayNG
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
+        #git remote add DHR60 https://github.com/DHR60/V2rayNG.git
+        #echo "Pref dnshost"
+        #git fetch DHR60 self_use_build
+        #git cherry-pick 6ce76ce4b3665ac60cb1fab42620c85afc1e66ff || true
+
         git remote add DHR60 https://github.com/DHR60/V2rayNG.git
-        echo "Pref dnshost"
         git fetch DHR60 self_use_build
-        git cherry-pick 6ce76ce4b3665ac60cb1fab42620c85afc1e66ff || true
+
+        DNS_HOST_SHA=$(git log DHR60/self_use_build --grep="perf. dns host" --format="%H" -n 1)
+
+        if [ -n "$DNS_HOST_SHA" ]; then
+         echo "Found commit: $DNS_HOST_SHA"
+         git cherry-pick $DNS_HOST_SHA || true
+        else
+        echo "Error: No commit found with message 'perf. dns host'"
+        fi
+
         #echo "Force Close core"
         #git cherry-pick de53c9af23c028167a4618471f1e34f50004957e || true
 
